name: Deploying FastAPI App to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/fetalhealthapp  --project=${{ secrets.PROJECT_ID }}
        gcloud run deploy fetalhealthapp \
          --image gcr.io/${{ secrets.PROJECT_ID }}/fetalhealthapp \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated
