name: Deploying FastAPI App to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

    - name: Deploy to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/fetalhealthapp  --project=${{ secrets.PROJECT_ID }}
        gcloud run deploy fetalhealthapp \
          --image gcr.io/${{ secrets.PROJECT_ID }}/fetalhealthapp \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated
